

# This file was *autogenerated* from the file 23.sage
from sage.all_cmdline import *   # import sage library

_sage_const_23 = Integer(23); _sage_const_200000 = Integer(200000); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_1000 = Integer(1000); _sage_const_0 = Integer(0)
from sage.all import *
import sys

def cazar_numero_congruente(objetivo=_sage_const_23 , max_n=_sage_const_200000 ):
    print(f"=== BUSCADOR ESPECÍFICO DE SEMILLAS PARA N={objetivo} ===")
    print(f"Buscando en rango n=[1, {max_n}] usando f(n,m) = n(n-m)(2n-m)(3n-m)")
    
    encontrado = False
    
    # Optimizamos: m siempre es menor que n en tu operador
    for n in range(_sage_const_1 , max_n + _sage_const_1 ):
        # El ratio m/n suele ser clave. Probamos m desde 1 hasta n-1
        for m in range(_sage_const_1 , n):
            # Tu fórmula k=3
            N = n * (n - m) * (_sage_const_2 *n - m) * (_sage_const_3 *n - m)
            
            # Extraemos el núcleo square-free
            # N.squarefree_part() es mucho más rápido que un bucle manual
            if N.squarefree_part() == objetivo:
                print(f"\n¡ÉXITO! Semilla encontrada:")
                print(f"n = {n}")
                print(f"m = {m}")
                print(f"Área N generada = {N}")
                print(f"Verificación: {N} / {objetivo} = {N/objetivo} (debe ser un cuadrado perfecto)")
                
                # Verificamos si es cuadrado perfecto
                if (N/objetivo).is_square():
                    raiz = sqrt(N/objetivo)
                    print(f"Factor cuadrado s^2 = {raiz}^2")
                
                encontrado = True
                break
        
        if encontrado: break
        
        # Monitor de progreso
        if n % _sage_const_1000  == _sage_const_0 :
            sys.stdout.write(f"\rRevisado hasta n={n}...")
            sys.stdout.flush()

    if not encontrado:
        print(f"\nNo se encontró la semilla en el rango n={max_n}. ")
        print("Esto sugiere que el 23 requiere parámetros aún más grandes o un ratio m/n específico.")

# Ejecutar búsqueda
cazar_numero_congruente(_sage_const_23 )

