

# This file was *autogenerated* from the file direct_rawcov.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2000000 = Integer(2000000); _sage_const_1000000 = Integer(1000000); _sage_const_100 = Integer(100); _sage_const_50 = Integer(50); _sage_const_5 = Integer(5)
import csv
import requests
from sage.all import *

def cargar_oeis_bruto():
    url = "https://oeis.org/A003273/b003273.txt"
    print("1. Cargando lista OEIS bruta (5742 números)...")
    response = requests.get(url)
    lineas = response.text.strip().split('\n')
    
    oeis_raw_set = set()
    for line in lineas:
        if line.startswith('#') or not line.strip(): continue
        partes = line.split()
        if len(partes) >= _sage_const_2 :
            oeis_raw_set.add(Integer(partes[_sage_const_1 ]))
    return oeis_raw_set

def analisis_bruto_rapido(archivo_csv, oeis_raw):
    hits_directos = set()
    total_filas = _sage_const_0 
    
    print(f"2. Iniciando búsqueda de identidad directa en: {archivo_csv}")
    
    try:
        with open(archivo_csv, 'r') as f:
            reader = csv.DictReader(f)
            for row in reader:
                try:
                    # Comparación directa de N sin procesar nada más
                    valor_N = Integer(row['N'])
                    
                    if valor_N in oeis_raw:
                        hits_directos.add(valor_N)
                    
                    total_filas += _sage_const_1 
                    if total_filas % _sage_const_2000000  == _sage_const_0 :
                        print(f"   ... {total_filas//_sage_const_1000000 }M filas revisadas. Hits brutos: {len(hits_directos)}")
                except:
                    continue
                    
    except FileNotFoundError:
        print("Error: Archivo no encontrado.")
        return

    # Reporte final corregido (usando float() para evitar el TypeError)
    n_hits = len(hits_directos)
    n_total_oeis = len(oeis_raw)
    porcentaje = float(n_hits / n_total_oeis) * _sage_const_100 

    print("\n" + "="*_sage_const_50 )
    print("RESULTADO ANALISIS BRUTO (IDENTIDAD DIRECTA)")
    print("="*_sage_const_50 )
    print(f"Total registros en data:     {total_filas}")
    print(f"Universo OEIS Bruto:         {n_total_oeis}")
    print(f"Hits encontrados (N = OEIS): {n_hits}")
    print(f"Cobertura Bruta:             {porcentaje:.4f}%")
    print("="*_sage_const_50 )
    
    if n_hits > _sage_const_0 :
        print("\nPrimeros 5 hits brutos encontrados:")
        print(sorted(list(hits_directos))[:_sage_const_5 ])

# Ejecución
oeis_raw = cargar_oeis_bruto()
analisis_bruto_rapido('db_k3_gigante_ratio_autosave.csv', oeis_raw)

