

# This file was *autogenerated* from the file k3_mhalf.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_8 = Integer(8); _sage_const_100 = Integer(100); _sage_const_0 = Integer(0); _sage_const_1000 = Integer(1000)
import csv
from sage.all import *

# Nombre del archivo de salida
output_file = "operador_n_n2.csv"

def generar_serie_fraccional(limite_n):
    print(f"Iniciando generación hasta n={limite_n} con salto m=n/2...")
    
    with open(output_file, 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(['n', 'valor_bruto', 'N_pure', 'clase_mod8'])
        
        for n_val in range(_sage_const_2 , limite_n + _sage_const_1 ):
            n = Integer(n_val)
            
            # Definición de la fórmula: n * (n - n/2) * (2n - n/2) * (3n - n/2)
            # Simplificación algebraica: n * (n/2) * (3n/2) * (5n/2) = (15/8) * n^4
            term1 = n
            term2 = n - n/_sage_const_2 
            term3 = _sage_const_2 *n - n/_sage_const_2 
            term4 = _sage_const_3 *n - n/_sage_const_2 
            
            valor_bruto_racional = term1 * term2 * term3 * term4
            
            # Solo procesamos si el resultado es un entero (importante para SF)
            # Nota: n^4 * 15/8 requiere que n sea par para ser entero
            if valor_bruto_racional.is_integer():
                valor_bruto = Integer(valor_bruto_racional)
                n_pure = valor_bruto.squarefree_part()
                clase = n_pure % _sage_const_8 
                
                writer.writerow([n_val, valor_bruto, n_pure, clase])
            
            if n_val % _sage_const_100  == _sage_const_0 :
                print(f"Procesado hasta n={n_val}...")

    print(f"\nArchivo '{output_file}' generado con éxito.")

# Ejecución para n de 2 a 1000
generar_serie_fraccional(_sage_const_1000 )

