

# This file was *autogenerated* from the file m_maxmin_minusplus2to4.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_55 = Integer(55); _sage_const_0 = Integer(0); _sage_const_1001 = Integer(1001); _sage_const_100 = Integer(100)
import requests
import pandas as pd

# 1. Preparación de referencia OEIS (A003273)
print("Cargando referencia OEIS A003273...")
url_oeis = "https://oeis.org/A003273/b003273.txt"
response = requests.get(url_oeis)
oeis_sf = set()
for line in response.text.splitlines():
    if line and not line.startswith('#'):
        val = int(line.split()[_sage_const_1 ])
        oeis_sf.add(int(squarefree_part(val)))

# 2. Construcción expandida (Dinámicos + Estáticos)
resultados_totales = set()
analisis_por_m = []

# Definición de los 8 regímenes de m
regimenes = [
    ('n-1', lambda n: n - _sage_const_1 ),
    ('n-2', lambda n: n - _sage_const_2 ),
    ('n-3', lambda n: n - _sage_const_3 ),
    ('n-4', lambda n: n - _sage_const_4 ),
    ('m=1', lambda n: _sage_const_1 ),
    ('m=2', lambda n: _sage_const_2 ),
    ('m=3', lambda n: _sage_const_3 ),
    ('m=4', lambda n: _sage_const_4 )
]

print(f"{'Régimen':<10} | {'Generados':<10} | {'Nuevos SF':<10} | {'Match OEIS':<10}")
print("-" * _sage_const_55 )

for etiqueta, func_m in regimenes:
    nuevos_en_esta_corrida = set()
    total_generados_m = _sage_const_0 
    
    for n in range(_sage_const_2 , _sage_const_1001 ):
        m = func_m(n)
        # Evitar valores no positivos o n=m (que anularía el producto)
        if m <= _sage_const_0  or n == m: continue 
        
        # Operador: n(n-m)(2n-m)(3n-m)
        raw_N = n * (n - m) * (_sage_const_2 *n - m) * (_sage_const_3 *n - m)
        sf_N = int(squarefree_part(raw_N))
        
        total_generados_m += _sage_const_1 
        
        # Exclusión secuencial
        if sf_N not in resultados_totales:
            nuevos_en_esta_corrida.add(sf_N)
    
    # Contraste OEIS
    matches = nuevos_en_esta_corrida.intersection(oeis_sf)
    
    analisis_por_m.append({
        'm': etiqueta,
        'generados': total_generados_m,
        'nuevos_sf': len(nuevos_en_esta_corrida),
        'matches_oeis': len(matches)
    })
    
    print(f"{etiqueta:<10} | {total_generados_m:<10} | {len(nuevos_en_esta_corrida):<10} | {len(matches):<10}")
    resultados_totales.update(nuevos_en_esta_corrida)

# 3. Consolidado
total_sf = len(resultados_totales)
total_matches = sum(d['matches_oeis'] for d in analisis_por_m)

print("-" * _sage_const_55 )
print(f"Total Núcleos Únicos (SF): {total_sf}")
print(f"Total Coincidencias OEIS:  {total_matches}")
if total_sf > _sage_const_0 :
    print(f"Precisión Global:          {float(total_matches/total_sf)*_sage_const_100 :.2f}%")

