

# This file was *autogenerated* from the file maxmin_minusplus_half.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_60 = Integer(60); _sage_const_0 = Integer(0); _sage_const_1001 = Integer(1001); _sage_const_100 = Integer(100)
import requests

# 1. OEIS con Square-Free
print("Cargando referencia OEIS A003273...")
url_oeis = "https://oeis.org/A003273/b003273.txt"
response = requests.get(url_oeis)
oeis_sf = set(ZZ(line.split()[_sage_const_1 ]).squarefree_part() for line in response.text.splitlines() if line and not line.startswith('#'))

# 2. Evaluación Independiente
regimenes = [
    ('n-1', lambda n: n - _sage_const_1 ), ('n-2', lambda n: n - _sage_const_2 ), ('n-3', lambda n: n - _sage_const_3 ), ('n-4', lambda n: n - _sage_const_4 ),
    ('m=1', lambda n: _sage_const_1 ), ('m=2', lambda n: _sage_const_2 ), ('m=3', lambda n: _sage_const_3 ), ('m=4', lambda n: _sage_const_4 ),
    ('n/2+1', lambda n: n//_sage_const_2  + _sage_const_1 ), ('n/2+2', lambda n: n//_sage_const_2  + _sage_const_2 ), ('n/2+3', lambda n: n//_sage_const_2  + _sage_const_3 ), ('n/2+4', lambda n: n//_sage_const_2  + _sage_const_4 )
]

print(f"\n{'Régimen':<10} | {'Unicos SF':<10} | {'Match OEIS':<10} | {'% Cobertura'}")
print("-" * _sage_const_60 )

total_unique_all_time = set()
suma_matches_brutos = _sage_const_0 

for etiqueta, func_m in regimenes:
    nucleos_regimen = set()
    for n in range(_sage_const_2 , _sage_const_1001 ):
        m = func_m(n)
        if m <= _sage_const_0  or n == m: continue 
        sf_N = ZZ(n * (n - m) * (_sage_const_2 *n - m) * (_sage_const_3 *n - m)).squarefree_part()
        nucleos_regimen.add(sf_N)
    
    matches = nucleos_regimen.intersection(oeis_sf)
    suma_matches_brutos += len(matches)
    total_unique_all_time.update(nucleos_regimen)
    
    print(f"{etiqueta:<10} | {len(nucleos_regimen):<10} | {len(matches):<10} | {float(len(matches)/len(nucleos_regimen)*_sage_const_100 ):.2f}%")

print("-" * _sage_const_60 )
print(f"Total núcleos únicos combinados: {len(total_unique_all_time)}")
print(f"Total coincidencias únicas con OEIS: {len(total_unique_all_time.intersection(oeis_sf))}")

