

# This file was *autogenerated* from the file mn_distribution.sage
from sage.all_cmdline import *   # import sage library

_sage_const_50 = Integer(50); _sage_const_10 = Integer(10); _sage_const_6 = Integer(6); _sage_const_100 = Integer(100); _sage_const_0p4 = RealNumber('0.4'); _sage_const_30 = Integer(30); _sage_const_0p7 = RealNumber('0.7'); _sage_const_2 = Integer(2); _sage_const_0p6 = RealNumber('0.6'); _sage_const_300 = Integer(300)
import pandas as pd
import matplotlib.pyplot as plt
from sage.all import *

# 1. Carga de datos optimizada
file_path = 'db_k3_gigante_ratio_autosave.csv'
try:
    # Leemos el archivo. Si tiene encabezados, pandas los detectará. 
    # Si no los tiene, los asignamos.
    df = pd.read_csv(file_path)
    
    # Mapeo de columnas basado en tu script k3_mes.sage.py
    # sf, n, m, ratio, es_oeis
    expected_cols = ['sf', 'n_param', 'm_param', 'ratio', 'es_oeis']
    
    if len(df.columns) == len(expected_cols):
        df.columns = expected_cols
    
    df['ratio'] = pd.to_numeric(df['ratio'], errors='coerce')
    print(f"Successfully loaded {len(df)} records.")
except Exception as e:
    print(f"Error al cargar el archivo: {e}")

def perform_ratio_analysis(data):
    # Limpiar datos nulos si los hay
    data = data.dropna(subset=['ratio'])
    
    # 2. Estadísticas Descriptivas
    stats = data['ratio'].describe()
    skewness = data['ratio'].skew()
    kurtosis = data['ratio'].kurtosis()
    
    print("-" * _sage_const_50 )
    print("GLOBAL RATIO m/n STATISTICAL SUMMARY")
    print("-" * _sage_const_50 )
    print(stats)
    print(f"Skewness: {skewness:.4f}")
    print(f"Kurtosis: {kurtosis:.4f}")
    
    # 3. Filtrar OEIS
    # Convertimos a string y comparamos para evitar problemas de tipos
    oeis_subset = data[data['es_oeis'].astype(str).str.upper() == 'TRUE']
    
    print("\n" + "-" * _sage_const_50 )
    print("OEIS SUBSET CHARACTERIZATION (HITS)")
    print("-" * _sage_const_50 )
    if not oeis_subset.empty:
        print(oeis_subset['ratio'].describe())
    else:
        print("No OEIS matches found in 'es_oeis' column.")

    # 4. Visualización Profesional
    plt.figure(figsize=(_sage_const_10 , _sage_const_6 ))
    
    # Histograma Global
    plt.hist(data['ratio'], bins=_sage_const_100 , density=True, alpha=_sage_const_0p4 , color='gray', label='Candidate Population')
    
    # Histograma OEIS (Hits)
    if not oeis_subset.empty:
        plt.hist(oeis_subset['ratio'], bins=_sage_const_30 , density=True, alpha=_sage_const_0p7 , color='navy', label='Confirmed OEIS-91')
        
        # Añadir línea de la media de los hits
        plt.axvline(oeis_subset['ratio'].mean(), color='red', linestyle='dashed', linewidth=_sage_const_2 , 
                    label=f"Mean OEIS Ratio: {oeis_subset['ratio'].mean():.4f}")
    
    plt.title(r"Comparison of $m/n$ Ratios: Total Search vs. OEIS Hits")
    plt.xlabel(r"Parameter Ratio ($m/n$)")
    plt.ylabel("Probability Density")
    plt.legend()
    plt.grid(True, linestyle=':', alpha=_sage_const_0p6 )
    
    output_img = "ratio_distribution_analysis.png"
    plt.savefig(output_img, dpi=_sage_const_300 )
    print(f"\n[ANALYSIS COMPLETE] Graphic saved as '{output_img}'")

if 'df' in locals():
    perform_ratio_analysis(df)

