

# This file was *autogenerated* from the file modular_distrib_sf.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_8 = Integer(8); _sage_const_0 = Integer(0); _sage_const_500000 = Integer(500000); _sage_const_1 = Integer(1); _sage_const_60 = Integer(60); _sage_const_100 = Integer(100)
import pandas as pd
import numpy as np
from sage.all import *
import sys

def analizar_distribucion_sf(archivo_csv):
    print(f"--- Iniciando Análisis Square-Free y Modular (Monitoreo Activo) ---")
    sys.stdout.flush() # Forzar salida en terminal
    
    conteos_sf = {_sage_const_3 : {}, _sage_const_8 : {}}
    total_registros = _sage_const_0 
    archivo_salida = 'db_k3_cores.csv'
    
    try:
        chunk_size_val = int(_sage_const_500000 )
        with open(archivo_salida, 'w') as f_out:
            f_out.write("sf_core\n")
            
            for chunk in pd.read_csv(archivo_csv, chunksize=chunk_size_val):
                # Extraemos la columna 'N'
                areas = chunk['N'].tolist()
                sf_batch = []
                
                for val in areas:
                    # Cálculo Square-free (esto es lo que consume tiempo)
                    n_sf = Integer(val).squarefree_part()
                    sf_batch.append(str(n_sf))
                    
                    # Conteos modulares
                    for m in [_sage_const_3 , _sage_const_8 ]:
                        res = int(n_sf % m)
                        conteos_sf[m][res] = conteos_sf[m].get(res, _sage_const_0 ) + _sage_const_1 
                    total_registros += _sage_const_1 
                
                # Guardado inmediato y reporte de progreso
                f_out.write("\n".join(sf_batch) + "\n")
                print(f"   [PROGRESO] {total_registros:,} registros procesados...")
                sys.stdout.flush() # Asegura que veas el progreso en WSL inmediatamente

        # --- REPORTE FINAL (DENTRO DE LA FUNCIÓN) ---
        print("\n" + "="*_sage_const_60 )
        print(f"AUDITORÍA DE NÚCLEOS SQUARE-FREE (N={int(total_registros):,})")
        print("="*_sage_const_60 )
        
        for mod in [_sage_const_8 , _sage_const_3 ]:
            label = "DENSIDAD DE SMITH" if mod == _sage_const_8  else "ESTRUCTURA PITAGÓRICA"
            print(f"\n[MOD {mod} - {label}]")
            f_actual = conteos_sf[mod]
            # Ordenar por residuo para consistencia
            for res in sorted(f_actual.keys()):
                count = f_actual[res]
                porcentaje = float(count / total_registros) * _sage_const_100 
                print(f"  {int(res)} ≡ (mod {mod}): {int(count):10,} ({porcentaje:6.2f}%)")

        print("\n" + "="*_sage_const_60 )
        print(f"✓ Archivo generado: {archivo_salida}")

    except Exception as e:
        print(f"✗ Error durante el proceso: {e}")

if __name__ == "__main__":
    # Asegúrate de que el nombre del CSV sea el correcto
    analizar_distribucion_sf('db_k3_no_restric_autosave.csv')

