

# This file was *autogenerated* from the file n_max.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1000 = Integer(1000); _sage_const_100000 = Integer(100000); _sage_const_50 = Integer(50)
import csv
from sage.all import *

archivo_csv = 'db_k3_gigante_ratio_autosave.csv'
tus_sf = {}  # Usamos diccionario para mapear sf -> n_original
max_n_param = _sage_const_0 

print("Analizando base de datos para encontrar el n máximo...")

with open(archivo_csv, 'r') as f:
    reader = csv.DictReader(f)
    for i, row in enumerate(reader):
        n_orig = Integer(row['n'])
        n_pure = n_orig.squarefree_part()
        
        # Filtro de auditoría
        if n_pure <= _sage_const_1000 :
            tus_sf[n_pure] = n_orig
            # Actualizamos el n máximo global que cumplió la condición
            if n_orig > max_n_param:
                max_n_param = n_orig
        
        if i % _sage_const_100000  == _sage_const_0  and i > _sage_const_0 :
            print(f"   ... {i} filas procesadas. n actual: {n_orig}")

print("\n" + "="*_sage_const_50 )
print("REPORTE DE TRAZABILIDAD")
print("="*_sage_const_50 )
print(f"Total de núcleos únicos encontrados (<=1000): {len(tus_sf)}")
print(f"Valor máximo de 'n' (parámetro) en el CSV que produjo un sf <= 1000:")
print(f"n_max = {max_n_param}")
print(f"Magnitud de n_max: {float(max_n_param):.2e}")
print("="*_sage_const_50 )

# Opcional: ver qué n_orig produjo un sf específico, ej: el 361
# print(f"n que produjo el sf 361: {tus_sf.get(361)}")

