

# This file was *autogenerated* from the file OEIS_10k_CORRECTED.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_50 = Integer(50); _sage_const_10000 = Integer(10000); _sage_const_500000 = Integer(500000); _sage_const_60 = Integer(60); _sage_const_100 = Integer(100); _sage_const_3503 = Integer(3503); _sage_const_10 = Integer(10)
import csv
import requests
from sage.all import *

# 1. Carga el universo de números de la OEIS
def cargar_oeis_completa():
    url = "https://oeis.org/A003273/b003273.txt"
    print(f"Descargando datos oficiales de OEIS (primeros ~5,742 números)...")
    response = requests.get(url)
    lineas = response.text.strip().split('\n')
    
    oeis_raw = []
    oeis_sf = set()
    
    for line in lineas:
        if line.startswith('#') or not line.strip(): 
            continue
        partes = line.split()
        if len(partes) >= _sage_const_2 :
            val = Integer(partes[_sage_const_1 ])  # El número congruente de la lista
            oeis_raw.append(val)
            oeis_sf.add(val.squarefree_part())  # Su núcleo SF
    
    print(f"OEIS raw cargados: {len(oeis_raw)}")
    print(f"OEIS cores SF únicos: {len(oeis_sf)}")
    print(f"Máximo valor OEIS raw: {max(oeis_raw)}")
    print(f"Máximo core SF OEIS: {max(oeis_sf)}")
    
    return oeis_raw, oeis_sf

# 2. Auditoría CORREGIDA - Sin filtro por límite superior erróneo
def auditar_operador_corregido(archivo_csv, oeis_raw, oeis_sf):
    """
    CORRECCIÓN: No filtramos por límite superior de valores raw.
    Comparamos TODOS los cores SF del operador vs TODOS los cores SF de OEIS.
    """
    hits_sf = set()
    total_generados_sf = set()
    max_n_procesado = _sage_const_0 
    count = _sage_const_0 
    
    # Estadísticas adicionales
    valores_sobre_10k = _sage_const_0 
    cores_sobre_10k = _sage_const_0 

    print(f"\nIniciando lectura de: {archivo_csv}...")
    print("CORRECCIÓN APLICADA: Sin filtro por max(oeis_raw)")
    print("-" * _sage_const_50 )
    
    try:
        with open(archivo_csv, 'r') as f:
            reader = csv.DictReader(f)  # Lee: N,n,m,Ratio_m_n...
            
            for row in reader:
                try:
                    # N = Resultado del operador (Área)
                    # n = Parámetro de entrada
                    area_real = Integer(row['N']) 
                    param_n = Integer(row['n'])
                    
                    # Calculamos el núcleo SF del RESULTADO 'N'
                    sf_actual = area_real.squarefree_part()
                    
                    # === CORRECCIÓN PRINCIPAL ===
                    # NO filtramos por límite superior
                    # Agregamos TODOS los cores SF generados
                    total_generados_sf.add(sf_actual)
                    
                    # Verificamos si está en OEIS
                    if sf_actual in oeis_sf:
                        hits_sf.add(sf_actual)
                    
                    # Estadísticas adicionales
                    if area_real > _sage_const_10000 :
                        valores_sobre_10k += _sage_const_1 
                    if sf_actual > _sage_const_10000 :
                        cores_sobre_10k += _sage_const_1 
                    
                    # Registro del avance del parámetro
                    if param_n > max_n_procesado:
                        max_n_procesado = param_n

                    count += _sage_const_1 
                    if count % _sage_const_500000  == _sage_const_0 :
                        print(f"Filas: {count:,} | Último N: {area_real} | Param n: {param_n}")
                        print(f"  → Cores SF únicos: {len(total_generados_sf):,} | Matches OEIS: {len(hits_sf):,}")

                except (ValueError, KeyError):
                    continue

    except FileNotFoundError:
        print(f"Error: No se encontró {archivo_csv}")
        return

    # === REPORTE FINAL (FORMATO COMPATIBLE CON STATA) ===
    print("\n" + "=" * _sage_const_60 )
    print("AUDITORÍA FINAL - COMPARACIÓN CON STATA")
    print("=" * _sage_const_60 )
    
    print("\n1. DATOS OEIS:")
    print(f"   Raw list: {len(oeis_raw):,} números")
    print(f"   Cores SF únicos: {len(oeis_sf):,}")
    
    print("\n2. DATOS OPERADOR k=3:")
    print(f"   Total registros procesados: {count:,}")
    print(f"   Cores SF únicos generados: {len(total_generados_sf):,}")
    print(f"   Valores N > 10,000: {valores_sobre_10k:,}")
    print(f"   Cores SF > 10,000: {cores_sobre_10k:,}")
    print(f"   Máximo parámetro n: {max_n_procesado}")
    
    print("\n3. MATCHING RESULTS:")
    print(f"   OEIS cores matched: {len(hits_sf):,} / {len(oeis_sf):,}")
    print(f"   OEIS cores NOT found: {len(oeis_sf) - len(hits_sf):,}")
    
    cobertura = (len(hits_sf) / len(oeis_sf)) * _sage_const_100  if len(oeis_sf) > _sage_const_0  else _sage_const_0 
    print(f"\n   ★ COBERTURA: {cobertura:.2f}%")
    
    if total_generados_sf:
        eficiencia = (len(hits_sf) / len(total_generados_sf)) * _sage_const_100 
        print(f"   Eficiencia (Hits/Generados): {eficiencia:.2f}%")
    
    # Verificación crítica
    print("\n4. VERIFICACIÓN vs STATA:")
    print(f"   Expected matches (Stata): 3,503")
    print(f"   Actual matches (Sage):    {len(hits_sf):,}")
    if len(hits_sf) == _sage_const_3503 :
        print("   ✓ RESULTADO CONSISTENTE CON STATA")
    else:
        print("   ✗ DISCREPANCIA DETECTADA")
    
    # Números faltantes (si hay)
    if len(hits_sf) < len(oeis_sf):
        faltantes = oeis_sf - hits_sf
        print(f"\n5. NÚMEROS OEIS NO ENCONTRADOS ({len(faltantes)}):")
        primeros_10 = sorted(list(faltantes))[:_sage_const_10 ]
        print(f"   Primeros 10: {primeros_10}")
    
    print("\n" + "=" * _sage_const_60 )
    
    return {
        'oeis_sf_total': len(oeis_sf),
        'operador_sf_total': len(total_generados_sf),
        'matches': len(hits_sf),
        'cobertura': cobertura,
        'max_n': max_n_procesado
    }

# === EJECUCIÓN ===
if __name__ == "__main__":
    print("ANÁLISIS CORREGIDO: k=3 Operator vs OEIS A003273")
    print("=" * _sage_const_60 )
    
    # Cargar OEIS
    oeis_raw, oeis_sf = cargar_oeis_completa()
    
    # Auditar con código corregido
    resultados = auditar_operador_corregido('db_k3_gigante_ratio_autosave.csv', oeis_raw, oeis_sf)
    
    # Resumen final
    print("\nRESUMEN EJECUTIVO:")
    print("-" * _sage_const_60 )
    print(f"El operador k=3 con n ≤ {resultados['max_n']} genera:")
    print(f"  • {resultados['matches']:,} / {resultados['oeis_sf_total']:,} cores OEIS")
    print(f"  • Cobertura: {resultados['cobertura']:.2f}%")
    print(f"  • Total cores únicos: {resultados['operador_sf_total']:,}")

