

# This file was *autogenerated* from the file tunnell_first.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1000 = Integer(1000); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_50 = Integer(50); _sage_const_100 = Integer(100)
import csv
from sage.all import *
import os

# --- CONFIGURACIÓN ---
ARCHIVO = 'db_k3_no_restric_autosave.csv'
LIMITE = _sage_const_1000 

def validacion_definitiva():
    print("--- INICIANDO VALIDACIÓN (MÉTODO POR RANGO DE CURVA) ---")
    
    if not os.path.exists(ARCHIVO):
        print("Error: No se encuentra el archivo CSV.")
        return

    hits = _sage_const_0 
    analizados = _sage_const_0 
    
    with open(ARCHIVO, 'r') as f:
        reader = csv.reader(f)
        try:
            next(reader) # Saltamos el encabezado 'N'
        except StopIteration:
            return

        for i, row in enumerate(reader):
            if i >= LIMITE: break
            
            try:
                N_val = Integer(row[_sage_const_0 ])
                n_sf = N_val.squarefree_part()
                
                if n_sf == _sage_const_1 :
                    continue

                # DEFINICIÓN PURA: n es congruente si y2 = x3 - n2x tiene rango > 0
                E = EllipticCurve([_sage_const_0 , _sage_const_0 , _sage_const_0 , -n_sf**_sage_const_2 , _sage_const_0 ])
                
                # mwrank es muy eficiente para estos números pequeños iniciales
                if E.rank(only_use_mwrank=True) > _sage_const_0 :
                    hits += _sage_const_1 
                    print(f"Registro {i+_sage_const_1 }: N={N_val} (sf={n_sf}) -> CONGRUENTE (Rank > 0)")
                
                analizados += _sage_const_1 
            except:
                continue

    print("\n" + "="*_sage_const_50 )
    print("RESULTADOS FINALES")
    print("-" * _sage_const_50 )
    print(f"Total analizados:   {analizados}")
    print(f"Congruentes (Hits): {hits}")
    if analizados > _sage_const_0 :
        print(f"Tasa de éxito:      {float(hits/analizados)*_sage_const_100 :.2f}%")
    print("="*_sage_const_50 )

if __name__ == "__main__":
    validacion_definitiva()

